### ISSUE TITLE
Support building on Go 1.6+

### ISSUE THREAD

**Issue by ipsi** [bluemixgaragelondon/cf-blue-green-deploy#13] opened 2016-07-15 20:27 UTC
As per the pull request #12, this project does not build on Go 1.6+. Instead, it gets the following error:

```
./main.go:173: cannot assign "github.com/nicksnyder/go-i18n/i18n".TranslateFunc to "github.com/cloudfoundry/cli/cf/i18n".T (type "github.com/cloudfoundry/cli/vendor/github.com/nicksnyder/go-i18n/i18n".TranslateFunc) in multiple assignment
```

This is caused by the lines:

```
    // T needs to point to a translate func, otherwise cf internals blow up
    i18n.T, _ = go_i18n.Tfunc("")
```

And is due to a change about how Go handles [vendored dependencies](https://blog.gopheracademy.com/advent-2015/vendor-folder/) in Go 1.6+. This is present in Go 1.5, but is off by default. It is on by default in Go 1.6, but can be turned off by setting `GO15VENDOREXPERIMENT` to `0`. It will be on by default in Go 1.7, and will not be able to be turned off.

The [suggested fix](https://github.com/cloudfoundry/cli/issues/889) for the issue is:

main.go:170

```
-       // T needs to point to a translate func, otherwise cf internals blow up
-       i18n.T, _ = go_i18n.Tfunc("")
```

manifest_test.go:15

```
+type localeGetter struct{}
+
+func (l localeGetter) Locale() string {
+       return "en-us"
+}
+
 var _ = Describe("Manifest reader", func() {
        // testing code that calls into cf cli requires T to point to a translate func
-       i18n.T, _ = go_i18n.Tfunc("")
+       i18n.T = i18n.Init(localeGetter{})
```

**Comment by holly-cummins** [comment] 2016-11-26 09:34
Thanks for investigating, @ipsi. It looks like the suggested change to main.go causes a null pointer problem later on in the cf internals. The unit tests pass, but the acceptance tests fail.  I traced through and I confirm that the issue is that the bgd code calls T, and we haven't initialised T, and apparently nothing else has initialised T, so panic ensues. 

I've reinstated the original code, so that we can resolve #11 and support CLI 6.22.1. This means that the plugin is back to not-compiling on go 1.6 and 1.7, but the built binary is functional. I'll follow up on the cf cli issue and see if there's an alternative fix to the issue you spotted about being able to assign to the vendored dependency package.

**Comment by holly-cummins** [comment] 2016-11-26 09:53
Looking at the [suggested fix](https://github.com/cloudfoundry/cli/issues/889) again, I think the right fix isn't to completely delete the line in main.go containing the assignment (as originally suggested), but instead to call i18n.Init([SOME SUITABLE LOCALE]) (like the suggested test change, but ideally with a more generic locale).

**Comment by bluemixgaragelondon** [comment] 2016-12-05 23:25
I've raised https://github.com/cloudfoundry/cli/issues/1018 with the cf cli fix. The only fix I'm aware of which doesn't cause null de-rereferences in the cf cli at runtime is to force the language to English. That doesn't feel right, so I'll hope there's a better solution.

**Comment by timjacobi** [comment] 2016-12-22 13:19
Looking at https://github.com/cloudfoundry/cli/issues/1018 we have two options:

- Write our own manifest reader
- Force the language to English

I would suggest we write our own manifest reader for the following reasons:

- As pointed out in https://github.com/cloudfoundry/cli/issues/1018 tapping into the CF internals is highly discouraged
- We only need one piece of code from the manifest reader
- We don't support I18N in this plugin anyway so why bother?

**Comment by holly-cummins** [comment] 2017-01-02 15:39
I agree - as a secondary benefit, removing our use of the CF internals should make us less sensitive to the exact version of the cf plugin being used, and more resilient to cf plugin upgrades.

**Comment by bluemixgaragelondon** [comment] 2017-01-26 16:25
The code changes which eliminate the dependency were done under c914bed872613322a11929e57e97816c82f3c16d (and improved in follow-on commits), so marking this closed.

**Closed by bluemixgaragelondon** 2017-01-26 16:25 UTC
